a=int(input("Enter the value of A "))
b=int(input("Enter the value of B "))
c=a+b
s=a-b
m=a*b
d=a/b
print("Addition =",c)
print("subtraction =",s)
print("Multiply =",m)
print("Division =",d)
